[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "IterFunc"
version = "0.0.8"
description = "ちょっと楽するために作ったライブラリ(超小機能)"
readme = "README.md"
license = {file="LICENSE"}
authors = [{name="つくも", email="0t0nashi0kayu@gmail.com"}]
